const DEFAULT_WAIT_INTERVAL_MS = 1000 * 10;
const FLAG_WAIT_INTERVAL_MS = 1000 * 30;
const STATUS_WAIT_INTERVAL_MS = 1000 * 60 * 5;
module.exports = {
  DEFAULT_WAIT_INTERVAL_MS,
  FLAG_WAIT_INTERVAL_MS,
  STATUS_WAIT_INTERVAL_MS,
};
